---
stages:
  - deploy
deploy:
  stage: deploy
  image: node:latest
  tags:
    - cd
  only:
    - staging
  script:
    - npm i
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
