---
stages:
  - deploy
deploy:
  stage: deploy
  image: node:latest
  tags:
    - cd
  environment:
    name: staging
    url: https://qarpa.netlify.app/
  only:
    - develop
  script:
    - npm i
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
      --prod
