default:
  image: ruby:16.14.0
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh

deploy:
  tags:
    - ci
  variables:
    FLY_API_TOKEN: $FLY_API_TOKEN
  script:
    - /root/.fly/bin/flyctl deploy
  only:
    - develop
