default:
  image: node:16.14.0
  before_script:
    - apt-get update -qq
    - apt-get install -y curl
    - curl https://fly.io/install.ps1 -useb | iex

deploy:
  tags:
    - ci
  variables:
    FLY_API_TOKEN: $FLY_API_TOKEN
  script:
    - /root/.fly/bin/flyctl deploy
  only:
    - develop
