---
# image: node:latest
# stages:
#   - setup
#   - build
#   - deploy
# setup:
#   stage: setup
#   tags:
#     - cd
#   script:
#     - npm ci
#   only:
#     - staging
# build:
#   stage: build
#   tags:
#     - cd
#   script:
#     - npm run build
#   artifacts:
#     paths:
#       - dist
#   only:
#     - staging
# deploy:
#   stage: deploy
#   tags:
#     - cd
#   script:
#     - npm i -g netlify-cli
#     - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
#   dependencies:
#     - build
#   only:
#     - staging
