---
stages:
  - deploy
deploy:
  stage: deploy
  image: node:latest
  tags:
    - cd
  # environment:
  #   name: production
  #   url: https://tescicd.netlify.app/
  only:
    - develop
  script:
    - npm i
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
      --prod
